# Generated by Django 3.2.6 on 2021-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('isbn', models.CharField(blank=True, max_length=255, verbose_name='ISBN')),
                ('authors', models.CharField(blank=True, max_length=255, verbose_name='Autores')),
                ('numberOfPages', models.SmallIntegerField(verbose_name='Numero de paginas')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Editora')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='País')),
                ('mediaType', models.CharField(blank=True, max_length=255, verbose_name='Tipo de Midia')),
                ('released', models.DateTimeField(verbose_name='Lançado')),
                ('povCharacters', models.JSONField(default=dict, verbose_name='Personagens Principais')),
                ('cover', models.TextField(blank=True, verbose_name='Capa')),
                ('linkToBuy', models.URLField(blank=True, verbose_name='Link pra compra')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('gender', models.CharField(max_length=8, verbose_name='Sexo')),
                ('culture', models.CharField(blank=True, max_length=255, verbose_name='Cultura')),
                ('born', models.CharField(blank=True, max_length=255, verbose_name='Nascido em')),
                ('died', models.CharField(blank=True, max_length=255, verbose_name='Morto em')),
                ('titles', models.JSONField(default=dict, verbose_name='Títulos')),
                ('aliases', models.JSONField(default=dict, verbose_name='Apelidos')),
                ('father', models.CharField(blank=True, max_length=255, verbose_name='Pai')),
                ('mother', models.CharField(blank=True, max_length=255, verbose_name='Mãe')),
                ('spouse', models.CharField(blank=True, max_length=255, verbose_name='Conjuge')),
                ('allegiances', models.JSONField(default=dict, verbose_name='Lealdades')),
                ('books', models.JSONField(default=dict, verbose_name='Livros')),
                ('povBooks', models.JSONField(default=dict, verbose_name='Livros Principais')),
                ('tvSeries', models.JSONField(default=dict, verbose_name='Aparicoes na serie')),
                ('playedBy', models.JSONField(default=dict, verbose_name='Ator')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
    ]
